### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by dolevdotan** [watson-developer-cloud/python-sdk#103]
I'm trying to install the library using `pip install --upgrade watson-developer-cloud` but getting the following error:

```
Collecting watson-developer-cloud
  Using cached watson-developer-cloud-0.19.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dotan\AppData\Local\Temp\pip-build-ry7ij62b\watson-developer-cloud\setup.py", line 63, in <module>
        long_description=read_md('README.md'),
      File "C:\Users\dotan\AppData\Local\Temp\pip-build-ry7ij62b\watson-developer-cloud\setup.py", line 40, in <lambda>
        read_md = lambda f: open(f, 'r').read()
      File "C:\Anaconda3\lib\encodings\cp1255.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 1896:
 character maps to <undefined>
    warning: pypandoc module not found, could not convert Markdown to RST

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\dotan\AppData\Local\Temp\pip-build-ry7ij62b\watson-developer-cloud\
```

This is on Windows 7 with python 3.4.3 / Anaconda 2.3.0 (64-bit).

**Comment by germanattanasio** [comment]
The warning is expected but the error looks pretty bad... I will look into it

**Comment by jsstylos** [comment]
Are you able to install other packages via pip? This seems like it might be related to missing systemtools in your environment: http://stackoverflow.com/questions/17886647/cant-install-via-pip-because-of-egg-info-error -- you could try `pip install --upgrade setuptools`
