### ISSUE TITLE
NLU example erroring out

### ISSUE THREAD

**Issue by belgort** [watson-developer-cloud/python-sdk#167]
Hello,

I see that NLU is now available on Bluemix. I gave it a try, creating new credentials and I'm receiving an error: https://www.dropbox.com/s/i3b9kwnq2rslbr8/Screenshot%202017-02-28%2010.17.50.png?dl=0

Any help you can provide would be appreciated.

**Comment by kognate** [comment]
I'm having trouble seeing that box link.  Can you paste in the error message as text?

**Comment by jsstylos** [comment]
There's a bug in the latest version of the SDK on pip that attempts to use a non-public service url. There will be a new release shortly.

**Comment by belgort** [comment]
Traceback (most recent call last):
  File "/Users/bruceelgort/Dropbox/bluemix/nlu.py", line 17, in <module>
    features=[features.Entities(), features.Keywords()])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/watson_developer_cloud/natural_language_understanding_v1.py", line 84, in analyze
    accept_json=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 320, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Unauthorized: Access is denied due to invalid credentials

**Comment by jsstylos** [comment]
Should be fixed now in 0.25.1

**Comment by belgort** [comment]
Yes it does now work. Thank you!
