### ISSUE TITLE
Issue parsing new url to conversation_v1.py

### ISSUE THREAD

**Issue by Cheppert** [watson-developer-cloud/python-sdk#188]
We're using the Watson services in Frankfurt, Germany. The WCS in Germany has another gateway url. So we tried to parse a new url to the conversation_v1.py using url=https://gateway-fra.watsonplatform.net/conversation/api'. But we're always getting the following error. We are using Python 2.7.11.

Traceback (most recent call last):
  File "examples/flowtest.py", line 45, in <module>
    results = ft.runFlowTest(workspace_id=workspace_id, flow=flow, show_progress=True)
  File "/Users/yanick/Documents/conversation-test-suite-master-welcoming/ConversationTestKit/flowtest_v1.py", line 131, in runFlowTest
    r = self.ctk.message(workspace_id=workspace_id, message_input=payload, context=context)
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/conversation_v1.py", line 181, in message
    json=data, accept_json=True)
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 298, in request
    **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:590)

**Comment by kognate** [comment]
I just setup a python 2.7 environment and was able to hit the German region conversation api if 
I installed pyOpenSSL

`pip install pyOpenSSL`

If I didn't have that installed, then I got the same error you show here.  If you can confirm that fixes the issue, I'll update the package and push a new version with the fixed requirements.

**Comment by Cheppert** [comment]
Working like a charm! Thanks for this fast support.
