### ISSUE TITLE
Speech to text

### ISSUE THREAD

**Issue by ahsen1402** [watson-developer-cloud/python-sdk#204]
Hi All,

thanks for the great api. I am getting errors when i upload files with size >= 100 mb and it returns an error? Any reason what the reason is or how do i solve it? Is the error on the python or IBM side. the error code is like this: 

```

---------------------------------------------------------------------------
SysCallError                              Traceback (most recent call last)
/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in _send_until_done(self, data)
    300             try:
--> 301                 return self.connection.send(data)
    302             except OpenSSL.SSL.WantWriteError:

/anaconda/lib/python3.6/site-packages/OpenSSL/SSL.py in send(self, buf, flags)
   1461         result = _lib.SSL_write(self._ssl, buf, len(buf))
-> 1462         self._raise_ssl_error(self._ssl, result)
   1463         return result

/anaconda/lib/python3.6/site-packages/OpenSSL/SSL.py in _raise_ssl_error(self, ssl, result)
   1369                     if errno != 0:
-> 1370                         raise SysCallError(errno, errorcode.get(errno))
   1371                 raise SysCallError(-1, "Unexpected EOF")

SysCallError: (32, 'EPIPE')

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    355         else:
--> 356             conn.request(method, url, **httplib_request_kw)
    357 

/anaconda/lib/python3.6/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1238         """Send a complete request to the server."""
-> 1239         self._send_request(method, url, body, headers, encode_chunked)
   1240 

/anaconda/lib/python3.6/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1284             body = _encode(body, 'body')
-> 1285         self.endheaders(body, encode_chunked=encode_chunked)
   1286 

/anaconda/lib/python3.6/http/client.py in endheaders(self, message_body, encode_chunked)
   1233             raise CannotSendHeader()
-> 1234         self._send_output(message_body, encode_chunked=encode_chunked)
   1235 

/anaconda/lib/python3.6/http/client.py in _send_output(self, message_body, encode_chunked)
   1064                         + b'\r\n'
-> 1065                 self.send(chunk)
   1066 

/anaconda/lib/python3.6/http/client.py in send(self, data)
    985         try:
--> 986             self.sock.sendall(data)
    987         except TypeError:

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in sendall(self, data)
    312         while total_sent < len(data):
--> 313             sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
    314             total_sent += sent

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in _send_until_done(self, data)
    307             except OpenSSL.SSL.SysCallError as e:
--> 308                 raise SocketError(str(e))
    309 

OSError: (32, 'EPIPE')

During handling of the above exception, another exception occurred:

ProtocolError                             Traceback (most recent call last)
/anaconda/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    437                     retries=self.max_retries,
--> 438                     timeout=timeout
    439                 )

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    648             retries = retries.increment(method, url, error=e, _pool=self,
--> 649                                         _stacktrace=sys.exc_info()[2])
    650             retries.sleep()

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    356             if read is False or not self._is_method_retryable(method):
--> 357                 raise six.reraise(type(error), error, _stacktrace)
    358             elif read is not None:

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py in reraise(tp, value, tb)
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    355         else:
--> 356             conn.request(method, url, **httplib_request_kw)
    357 

/anaconda/lib/python3.6/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1238         """Send a complete request to the server."""
-> 1239         self._send_request(method, url, body, headers, encode_chunked)
   1240 

/anaconda/lib/python3.6/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1284             body = _encode(body, 'body')
-> 1285         self.endheaders(body, encode_chunked=encode_chunked)
   1286 

/anaconda/lib/python3.6/http/client.py in endheaders(self, message_body, encode_chunked)
   1233             raise CannotSendHeader()
-> 1234         self._send_output(message_body, encode_chunked=encode_chunked)
   1235 

/anaconda/lib/python3.6/http/client.py in _send_output(self, message_body, encode_chunked)
   1064                         + b'\r\n'
-> 1065                 self.send(chunk)
   1066 

/anaconda/lib/python3.6/http/client.py in send(self, data)
    985         try:
--> 986             self.sock.sendall(data)
    987         except TypeError:

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in sendall(self, data)
    312         while total_sent < len(data):
--> 313             sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
    314             total_sent += sent

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in _send_until_done(self, data)
    307             except OpenSSL.SSL.SysCallError as e:
--> 308                 raise SocketError(str(e))
    309 

ProtocolError: ('Connection aborted.', OSError("(32, 'EPIPE')",))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-21-1bdf1d4a525c> in <module>()
----> 1 text1=speech_to_text.recognize(audio_file, content_type='audio/wav',timestamps=True,word_confidence=True,speaker_labels=True,continuous=True)

/anaconda/lib/python3.6/site-packages/watson_developer_cloud/speech_to_text_v1.py in recognize(self, audio, content_type, continuous, model, customization_id, inactivity_timeout, keywords, keywords_threshold, max_alternatives, word_alternatives_threshold, word_confidence, timestamps, interim_results, profanity_filter, smart_formatting, speaker_labels)
     60                             headers=headers,
     61                             data=audio, params=params,
---> 62                             stream=True, accept_json=True)
     63 
     64     def models(self):

/anaconda/lib/python3.6/site-packages/watson_developer_cloud/watson_developer_cloud_service.py in request(self, method, url, accept_json, headers, params, json, data, files, **kwargs)
    300                                     headers=headers,
    301                                     params=params, data=data, files=files,
--> 302                                     **kwargs)
    303 
    304         if 200 <= response.status_code <= 299:

/anaconda/lib/python3.6/site-packages/requests/api.py in request(method, url, **kwargs)
     56     # cases, and look like a memory leak in others.
     57     with sessions.Session() as session:
---> 58         return session.request(method=method, url=url, **kwargs)
     59 
     60 

/anaconda/lib/python3.6/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    516         }
    517         send_kwargs.update(settings)
--> 518         resp = self.send(prep, **send_kwargs)
    519 
    520         return resp

/anaconda/lib/python3.6/site-packages/requests/sessions.py in send(self, request, **kwargs)
    637 
    638         # Send the request
--> 639         r = adapter.send(request, **kwargs)
    640 
    641         # Total elapsed time of the request (approximately)

/anaconda/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    486 
    487         except (ProtocolError, socket.error) as err:
--> 488             raise ConnectionError(err, request=request)
    489 
    490         except MaxRetryError as e:

ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))
```

Thanks

Thanks

**Comment by ahsen1402** [comment]
I was able to fix above issue by setting continous=True and I was able to run one wav file correctly, however for the second one i get the error below. I have not changed anything in the code but the file name so I get this error, could this be related to the issue me being in the trial period yet?

```

---------------------------------------------------------------------------
SysCallError                              Traceback (most recent call last)
/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in _send_until_done(self, data)
    300             try:
--> 301                 return self.connection.send(data)
    302             except OpenSSL.SSL.WantWriteError:

/anaconda/lib/python3.6/site-packages/OpenSSL/SSL.py in send(self, buf, flags)
   1461         result = _lib.SSL_write(self._ssl, buf, len(buf))
-> 1462         self._raise_ssl_error(self._ssl, result)
   1463         return result

/anaconda/lib/python3.6/site-packages/OpenSSL/SSL.py in _raise_ssl_error(self, ssl, result)
   1369                     if errno != 0:
-> 1370                         raise SysCallError(errno, errorcode.get(errno))
   1371                 raise SysCallError(-1, "Unexpected EOF")

SysCallError: (32, 'EPIPE')

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    355         else:
--> 356             conn.request(method, url, **httplib_request_kw)
    357 

/anaconda/lib/python3.6/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1238         """Send a complete request to the server."""
-> 1239         self._send_request(method, url, body, headers, encode_chunked)
   1240 

/anaconda/lib/python3.6/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1284             body = _encode(body, 'body')
-> 1285         self.endheaders(body, encode_chunked=encode_chunked)
   1286 

/anaconda/lib/python3.6/http/client.py in endheaders(self, message_body, encode_chunked)
   1233             raise CannotSendHeader()
-> 1234         self._send_output(message_body, encode_chunked=encode_chunked)
   1235 

/anaconda/lib/python3.6/http/client.py in _send_output(self, message_body, encode_chunked)
   1064                         + b'\r\n'
-> 1065                 self.send(chunk)
   1066 

/anaconda/lib/python3.6/http/client.py in send(self, data)
    985         try:
--> 986             self.sock.sendall(data)
    987         except TypeError:

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in sendall(self, data)
    312         while total_sent < len(data):
--> 313             sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
    314             total_sent += sent

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in _send_until_done(self, data)
    307             except OpenSSL.SSL.SysCallError as e:
--> 308                 raise SocketError(str(e))
    309 

OSError: (32, 'EPIPE')

During handling of the above exception, another exception occurred:

ProtocolError                             Traceback (most recent call last)
/anaconda/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    437                     retries=self.max_retries,
--> 438                     timeout=timeout
    439                 )

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    648             retries = retries.increment(method, url, error=e, _pool=self,
--> 649                                         _stacktrace=sys.exc_info()[2])
    650             retries.sleep()

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    356             if read is False or not self._is_method_retryable(method):
--> 357                 raise six.reraise(type(error), error, _stacktrace)
    358             elif read is not None:

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py in reraise(tp, value, tb)
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    355         else:
--> 356             conn.request(method, url, **httplib_request_kw)
    357 

/anaconda/lib/python3.6/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1238         """Send a complete request to the server."""
-> 1239         self._send_request(method, url, body, headers, encode_chunked)
   1240 

/anaconda/lib/python3.6/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1284             body = _encode(body, 'body')
-> 1285         self.endheaders(body, encode_chunked=encode_chunked)
   1286 

/anaconda/lib/python3.6/http/client.py in endheaders(self, message_body, encode_chunked)
   1233             raise CannotSendHeader()
-> 1234         self._send_output(message_body, encode_chunked=encode_chunked)
   1235 

/anaconda/lib/python3.6/http/client.py in _send_output(self, message_body, encode_chunked)
   1064                         + b'\r\n'
-> 1065                 self.send(chunk)
   1066 

/anaconda/lib/python3.6/http/client.py in send(self, data)
    985         try:
--> 986             self.sock.sendall(data)
    987         except TypeError:

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in sendall(self, data)
    312         while total_sent < len(data):
--> 313             sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
    314             total_sent += sent

/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in _send_until_done(self, data)
    307             except OpenSSL.SSL.SysCallError as e:
--> 308                 raise SocketError(str(e))
    309 

ProtocolError: ('Connection aborted.', OSError("(32, 'EPIPE')",))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-21-1bdf1d4a525c> in <module>()
----> 1 text1=speech_to_text.recognize(audio_file, content_type='audio/wav',timestamps=True,word_confidence=True,speaker_labels=True,continuous=True)

/anaconda/lib/python3.6/site-packages/watson_developer_cloud/speech_to_text_v1.py in recognize(self, audio, content_type, continuous, model, customization_id, inactivity_timeout, keywords, keywords_threshold, max_alternatives, word_alternatives_threshold, word_confidence, timestamps, interim_results, profanity_filter, smart_formatting, speaker_labels)
     60                             headers=headers,
     61                             data=audio, params=params,
---> 62                             stream=True, accept_json=True)
     63 
     64     def models(self):

/anaconda/lib/python3.6/site-packages/watson_developer_cloud/watson_developer_cloud_service.py in request(self, method, url, accept_json, headers, params, json, data, files, **kwargs)
    300                                     headers=headers,
    301                                     params=params, data=data, files=files,
--> 302                                     **kwargs)
    303 
    304         if 200 <= response.status_code <= 299:

/anaconda/lib/python3.6/site-packages/requests/api.py in request(method, url, **kwargs)
     56     # cases, and look like a memory leak in others.
     57     with sessions.Session() as session:
---> 58         return session.request(method=method, url=url, **kwargs)
     59 
     60 

/anaconda/lib/python3.6/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    516         }
    517         send_kwargs.update(settings)
--> 518         resp = self.send(prep, **send_kwargs)
    519 
    520         return resp

/anaconda/lib/python3.6/site-packages/requests/sessions.py in send(self, request, **kwargs)
    637 
    638         # Send the request
--> 639         r = adapter.send(request, **kwargs)
    640 
    641         # Total elapsed time of the request (approximately)

/anaconda/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    486 
    487         except (ProtocolError, socket.error) as err:
--> 488             raise ConnectionError(err, request=request)
    489 
    490         except MaxRetryError as e:

ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))
```

**Comment by germanattanasio** [comment]
There is a 100MB limitation imposed by the service.

> With either approach, streaming or one-shot delivery, the service imposes a size limit of 100 MB on the audio data that you can transcribe at one time. When recognizing long continuous audio streams or large files, you can take the following steps to ensure that your audio does not exceed the 100 MB limit:

See: https://www.ibm.com/watson/developercloud/doc/speech-to-text/input.html#limits

**Comment by mrinalinihanagodu** [comment]
Hi,
I am getting an 'Unexpected EOF' error. I do not know what is causing this. Below is the Traceback.
Any idea how can I solve this???
`Traceback (most recent call last):
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanagodu\Documents\SelfTraining\VoiceAnalytics\myanalytics\voice\views.py", line 87, in create
    result=stt.recognize(x, content_type="audio/wav",keywords=["Roberts","sorry"],keywords_threshold=0.01,smart_formatting=True,speaker_labels=True,max_alternatives=3,inactivity_timeout=-1)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\watson_developer_cloud\speech_to_text_v1.py", line 63, in recognize
    stream=True, accept_json=True)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\watson_developer_cloud\watson_service.py", line 388, in request
    **kwargs)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error("(-1, 'Unexpected EOF')",))
(Thread-3 ) Internal Server Error: /audio/upload
Traceback (most recent call last):
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanagodu\Documents\SelfTraining\VoiceAnalytics\myanalytics\voice\views.py", line 87, in create
    result=stt.recognize(x, content_type="audio/wav",keywords=["Roberts","sorry"],keywords_threshold=0.01,smart_formatting=True,speaker_labels=True,max_alternatives=3,inactivity_timeout=-1)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\watson_developer_cloud\speech_to_text_v1.py", line 63, in recognize
    stream=True, accept_json=True)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\watson_developer_cloud\watson_service.py", line 388, in request
    **kwargs)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\hanagodu\Envs\voiceanalytics\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error("(-1, 'Unexpected EOF')",))`

**Comment by germanattanasio** [comment]
@mrinalinihanagodu did you see my reply?

**Comment by naeri77** [comment]
Hi there,
I am getting a similar error and the file I was trying to upload is 4MB.. Could you tell what could be causing this error.
Thanks,
Neha

Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/watson_developer_cloud/speech_to_text_v1.py", line 62, in recognize
    stream=True, accept_json=True)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 302, in request
    **kwargs)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(32, 'EPIPE')",))

**Comment by germanattanasio** [comment]
@naeri77 can you open a new issue and add steps to reproduce it? It's hard to find what the problem is if we can't reproduce it. This issue is closed because it was a user trying to upload a file > 100mb.
