### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte xxx in position xxx: invalid start byte

### ISSUE THREAD

**Issue by ezfranca** [watson-developer-cloud/python-sdk#230]
Hi, guys!
I have an app that worked fine on python 2.7. 

I needed to upgrade to python 3.4 and the speech to text stopped to work. 
Yes, I ported to my code to python 3 and everything but speech to text works fine. 
I am using pt-br language.

I waited until the release of 0.26.2 because it not worked on 0.25 and seem to still not work on new version. Can you help me ? Am I stuck with python 2.7 ?

Thank you

```
Traceback (most recent call last):
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/app/__main__.py", line 42, in facebook_route
    return chatbot_webhook.interfaces.facebook.webhook_fb(request)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/app/chatbot_webhook/interfaces/facebook/facebook_rules.py", line 70, in webhook_fb
    pergunta_txt = s2text(audio_url,'mp4')
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/app/chatbot_webhook/cloud_services/watson/s2text.py", line 47, in s2text
    word_confidence=True)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/watson_developer_cloud/speech_to_text_v1.py", line 62, in recognize
    stream=True, accept_json=True)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 302, in request
    **kwargs)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ez/projetos/brq/chatbot/brq-chatbot-webhook-py/venv-34/lib/python3.4/site-packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 967, in _send_output
    self.send(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 921, in send
    datablock = data.read(blocksize)
  File "/usr/lib64/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 14: invalid start byte
```

**Comment by ehdsouza** [comment]
@ezfranca can you paste the code which caused the issue. It would be very helpful to look into this issue.
