### ISSUE TITLE
Version parameter not included in Document Conversion Service

### ISSUE THREAD

**Issue by prevosti** [watson-developer-cloud/python-sdk#27]
The current version of the python-sdk doesn't add the required **version** parameter to the URL: 
https://gateway.watsonplatform.net/document-conversion/api/v1/convert_document?version=2016-02-10

The Exception being thrown looks like the following:

Traceback (most recent call last):
  File "document_conversion_v1.py", line 12, in <module>
    print(json.dumps(document_conversion.convert_document(document=document, config=config), indent=2))
  File "/usr/local/lib/python2.7/dist-packages/watson_developer_cloud/document_conversion_v1.py", line 36, in convert_document
    return self.request(method='POST', url='/v1/convert_document', files=files, accept_json=True)
  File "/usr/local/lib/python2.7/dist-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 250, in request
    raise WatsonException('Error: ' + error_message + ', Code: ' + str(response.status_code))
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: You must include a version parameter., Code: 400

**Comment by jsstylos** [comment]
Thanks for the report. There was a bug in the SDK that prevented the Document Conversion service from working. The 0.4.1 release should fix this issue.
