### ISSUE TITLE
Not able to run new version of watson-developer-cloud

### ISSUE THREAD

**Issue by drarvindsathi** [watson-developer-cloud/python-sdk#349]
What is the best version of `watson-developer-cloud`.  The Discovery document shows `0.26.1`.  I tried installing it and got the following error.  I am installing using Anaconda:

```
Exception:
Traceback (most recent call last):
  File "C:\Users\asathi\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\asathi\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\asathi\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\asathi\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\asathi\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\asathi\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\asathi\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Users\asathi\AppData\Local\Continuum\Anaconda3\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\asathi\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages\\cryptography\\hazmat\\bindings\\_constant_time.pyd'
```

**Comment by germanattanasio** [comment]
Try installing `>1.0.0`. The documentation is outdated.

**Comment by ehdsouza** [comment]
@drarvindsathi you may also want to use virtualenv.

```
pip install virtualenv
virtualenv ENV
source activate ENV/bin/activate
```

**Comment by germanattanasio** [comment]
I'm going to close this since it's not an issue. Feel free to reopen it.
