### ISSUE TITLE
Speech-to-Text : Unable to Connect

### ISSUE THREAD

**Issue by naeri77** [watson-developer-cloud/python-sdk#378]
Hi,
I am working on speech-to-text conversion using Google Compute Debian Linux VM. I am not able to connect using either CuRL or Python.

I am using the following code for CuRL:

```
curl -X POST -u USERNAME:PASSWORD \
  --header "Content-Type: audio/aac" \
  --data-binary "ComcastCall.mp3" \
  "https://stream.watsonplatform.net/speech-to-text/api"
```

and am getting the error:
```
{
  "error": "Your browser approached me (at /speech-to-text/api) with the method \"POST\".  I only allow the methods HEAD, GET here.",
  "code": 405,
"code_description": "Method Not Allowed"
}

For Python, the code, and error as below: 

```
sudo apt-get install python-pip
pip install simplejson
pip install -I watson-developer-cloud==0.26.1
```

```none
>>> import os
>>> import simplejson as json
>>> from os.path import join, dirname
>>> from watson_developer_cloud import SpeechToTextV1
>>> speech_to_text = SpeechToTextV1(
...     username='USERNAME',
...     password='PASSWORD'
... )
>>> with open(join(dirname("__file__"), 'ComcastCall.mp3'), 'rb') as audio_file:
...     data = json.dumps(speech_to_text.recognize(audio_file,        
...                       content_type='audio/aac', timestamps=False, 
...                           word_confidence=False, continuous=True), indent=2)
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/watson_developer_cloud/speech_to_text_v1.py", line 62, in recognize
    stream=True, accept_json=True)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 302, in request
    **kwargs)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/neha_aeri/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(32, 'EPIPE')",))
>>> 
```

The file I am trying to upload is around 4 MB. Could you help me understand what could be causing this?

**Comment by germanattanasio** [comment]
The curl command is missing the endpoint and the `--data-binary` value should start with `@`

This example should work:
```sh
curl -X POST -u "{username}":"{password}" \
--header "Content-Type: audio/flac" \
--data-binary "@ComcastCall.mp3" \
"https://stream.watsonplatform.net/speech-to-text/api/v1/recognize"
```

Regarding the python error, you are using an old version of the SDK. update it by running:
```
pip install --upgrade watson-developer-cloud
```
Then use this example https://github.com/watson-developer-cloud/python-sdk/blob/develop/examples/speech_to_text_v1.py

Make sure you update the content-type since you are sending an `.mp3` file.
