### ISSUE TITLE
create_classifier for NLC still broken?

### ISSUE THREAD

**Issue by Anwulika** [watson-developer-cloud/python-sdk#379]
#### Expected behavior
I'm following the API docs at [1] to create an NLC classifier
I tried to fix the error using the advice on this thread https://github.com/watson-developer-cloud/python-sdk/issues/307 , but it seems that I am not getting the fix seen by the OP when I call the API. Could it be that I am calling an old version of the API or that I am doing something else wrong? I only signed up last week so it would surprise me if versioning is the issue

#### Actual behavior

This is the error message I recieved:

```
Traceback (most recent call last):
  File "classifier.py", line 13, in <module>
    training_data=training_data
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/watson_developer_cloud/natural_language_classifier_v1.py", line 134, in create_classifier
    accept_json=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/watson_developer_cloud/watson_service.py", line 388, in request
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 496, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
AttributeError: 'dict' object has no attribute 'read'

```

#### Code snippet 

This is my python code:

```python
import json
from watson_developer_cloud import NaturalLanguageClassifierV1

natural_language_classifier = NaturalLanguageClassifierV1(
    username="xyz",
    password="xyz"
)

with open('data_v1.csv','rb') as training_data:
    metadata = {"name": "My Classifier", "language": "en"}
    classifier = natural_language_classifier.create_classifier(
    metadata=metadata,
    training_data=training_data
  )
print(json.dumps(classifier, indent=2))

```

#### python sdk version
Using Natural Language Understanding API 

#### python version
python 2.7.14

[1] https://www.ibm.com/watson/developercloud/natural-language-classifier/api/v1/?python#create_classifier

**Comment by ehdsouza** [comment]
Seems like you are using an older version of the sdk. The latest version is `1.0.2`

**Comment by Anwulika** [comment]
Thank you will give changing that a go.

Kind Regards,

Anwulika Elliott 
European Healthcare and Life Sciences Operations Manager
IBM Futures

E-mail: anwulika.elliott@ibm.com
Mobile: +447964392054

76 Upper Ground
London, SE19PZ
United Kingdom

**Comment by zxtonizx** [comment]
@ehdsouza thanks, I've had the same issue. How do you change the version of the sdk?

**Comment by zxtonizx** [comment]
Just to follow up with full information.

Using Python 2.7 and SDK 1.0.2 (which I'm pretty sure was already being used but now have confirmed). This is my code. 

```
from watson_developer_cloud import NaturalLanguageClassifierV1
import json

natural_language_classifier = NaturalLanguageClassifierV1(
    username="myNLCusername",
    password="myNLCpassword"
)

with open('weather_data_train.csv', 'rb') as training_data:
    metadata = {"name": "My Classifier", "language": "en"}
    classifier = natural_language_classifier.create_classifier(
    metadata=metadata,
    training_data=training_data
    )
    print(json.dumps(classifier, indent=2))
```
which returns

```
Traceback (most recent call last):
  File "classifier.py", line 15, in <module>
    training_data=training_data
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/natural_language_classifier_v1.py", line 134, in create_classifier
    accept_json=True)
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/watson_service.py", line 382, in request
    **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Python/2.7/site-packages/requests/models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "/Library/Python/2.7/site-packages/requests/models.py", line 496, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/Library/Python/2.7/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
AttributeError: 'dict' object has no attribute 'read'
```

I have also tried replacing
`metadata = {"name": "My Classifier", "language": "en"}`
with
`metadata = json.dumps({'name': 'My Classifier', 'language': 'en'})`

With returns

```
Traceback (most recent call last):
  File "classifier.py", line 15, in <module>
    training_data=training_data
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/natural_language_classifier_v1.py", line 134, in create_classifier
    accept_json=True)
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/watson_service.py", line 409, in request
    error_info)
watson_developer_cloud.watson_service.WatsonApiException: Error: Missing metadata, Code: 400

```
Any clues as to what might be going on?

**Comment by germanattanasio** [comment]
If you look at the `examples` folder. This should work

```pu
# create a classifier
with open('weather_data_train.csv', 'rb') as training_data:
    metadata = json.dumps({'name': 'my-classifier', 'language': 'en'})
    classifier = natural_language_classifier.create_classifier(
        metadata=metadata,
        metadata_filename='m.json',
        training_data=training_data
    )
    print(json.dumps(classifier, indent=2))
```

**Comment by germanattanasio** [comment]
@ehdsouza I think we need to have a default value for `metadata_filename`

**Comment by mkistler** [comment]
You should not need to specify a filename for `metadata` on `create_classifier`.

I don't know what is going on exactly, but this code works (for me) (Python 2.7, current "master" of Python SDK):
```
import json
import os
from watson_developer_cloud import NaturalLanguageClassifierV1

# Credentials will come from VCAP_SERVICES
natural_language_classifier = NaturalLanguageClassifierV1()

metadata = json.dumps({"name": "My Classifier", "language": "en"})

with open('weather_data_train.csv', 'rb') as training_data:
    classifier = natural_language_classifier.create_classifier(
        metadata=metadata,
        training_data=training_data
    )

print(json.dumps(classifier, indent=2))
```
The result:
```
{
  "status": "Training", 
  "name": "My Classifier", 
  "language": "en", 
  "created": "2018-02-28T04:16:06.900Z", 
  "url": "https://gateway.watsonplatform.net/natural-language-classifier/api/v1/classifiers/8fc193x296-nlc-3168", 
  "status_description": "The classifier instance is in its training phase, not yet ready to accept classify requests", 
  "classifier_id": "8fc193x296-nlc-3168"
}
```

**Comment by zxtonizx** [comment]
I have now resolved by creating a virtual environment and running the script in Python 3.6.3 instead of 2.7. Indeed a default value for `metadata_filename` was not necessary.

Perhaps this was an issue for Mac OS only (which I neglected to mention originally, sorry!)

If anyone else runs into the same issue, this is the code I used in command line to switch to a different Python version in a virtual environment:

```
virtualenv --python python3 env
source env/bin/activate
```

Thanks all for chipping in.

**Comment by gerinski** [comment]
I am having a similar issue with my code: I am running the following:

`def train_NLC(train_data, credentials, natural_language_classifier, nlc_name):
    # create a classifier
    with open(train_data, 'rb') as training_data:
        metadata = json.dumps({'name': 'topic', 'language': 'en'})
        nlc_instance = natural_language_classifier.create_classifier(metadata=metadata, training_data=training_data)
        print(json.dumps(nlc_instance, indent=2))
    credentials.change_val(nlc_name, nlc_instance['classifier_id'])`

I am getting the following error:
`File "/Users/ioannisgerochristos/Documents/mauritzhuisApp/gen_mauritshuis/querypipeline/NLC/NLC_tools.py", line 29, in train_NLC
    nlc_instance = natural_language_classifier.create_classifier(metadata=metadata, metadata_filename='m.json', training_data=training_data)
  File "/Users/ioannisgerochristos/Documents/mauritzhuisApp/gen_mauritshuis/virtualenv3/lib/python3.6/site-packages/watson_developer_cloud/natural_language_classifier_v1.py", line 134, in create_classifier
    accept_json=True)
  File "/Users/ioannisgerochristos/Documents/mauritzhuisApp/gen_mauritshuis/virtualenv3/lib/python3.6/site-packages/watson_developer_cloud/watson_service.py", line 415, in request
    error_info)
watson_developer_cloud.watson_service.WatsonApiException: Error: Entitlement error, Code: 400`

I am using python 3.6.4 and watson-developer-cloud 1.0.2.

I tried manually specifying the metadata_filename value, but still getting the same error
