### ISSUE TITLE
Watson Speech to text working only once

### ISSUE THREAD

**Issue by DrTardis1963** [watson-developer-cloud/python-sdk#429]
#### Expected behavior
transcribing what I say

#### Actual behavior

Traceback (most recent call last):
  File "/home/pi/K9/k9-chess-angular-master/python/working.py", line 10, in <module>
    import os, sys, subprocess, threading, time, json, re, signal, snowboydecoder, working
  File "/home/pi/K9/k9-chess-angular-master/python/working.py", line 139, in <module>
    speech_to_text.recognize_with_websocket(audio=f,content_type='audio/l16; rate=44100', recognize_callback=mycallback)
  File "/usr/local/lib/python2.7/dist-packages/watson_developer_cloud/speech_to_text_v1.py", line 279, in recognize_with_websocket
    RecognizeListener(audio, options, recognize_callback, url, headers)
  File "/usr/local/lib/python2.7/dist-packages/watson_developer_cloud/websocket/speech_to_text_websocket_listener.py", line 47, in __init__
    reactor.run() # pylint: disable=E1101
  File "/home/pi/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1242, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/home/pi/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1222, in startRunning
    ReactorBase.startRunning(self)
  File "/home/pi/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 730, in startRunning
    raise error.ReactorNotRestartable()
ReactorNotRestartable
>>> 

#### Steps to reproduce the problem
Run program, say something, wait for transcription, then say something again

#### Code snippet (Note: Do not paste your credentials)

with open('my_voice.wav') as f:
        speech_to_text.recognize_with_websocket(audio=f,content_type='audio/l16; rate=44100', recognize_callback=mycallback)
    while not finished:
        time.sleep(0.1)

#### python sdk version

2.7.13

#### python version

2

here is the program that creates the error

[proofofconcept.txt](https://github.com/watson-developer-cloud/python-sdk/files/1866115/proofofconcept.txt)

^ program (.py script)

| subroutine for text to speech (shell script)
V

[tts.txt](https://github.com/watson-developer-cloud/python-sdk/files/1866116/tts.txt)

Error appears after the second transcription begins

**Comment by ehdsouza** [comment]
Hi @DrTardis1963,

The `recognize_with_websocket ` right now is designed to take in the entire audio once and for all. Look at example: https://github.com/watson-developer-cloud/python-sdk/blob/develop/examples/microphone-speech-to-text.py

**Comment by germanattanasio** [comment]
@ehdsouza can we clarify this in the example so that users know that it won't allow them to send more audio after the initial recording?

**Comment by napomd** [comment]
@DrTardis1963  I experienced the same problem and it was because my params value was not included in the same function. See below:

`var SpeechToTextV1 = require('watson-developer-cloud/speech-to-text/v1');
var fs = require('fs');

var speech_to_text = new SpeechToTextV1 ({
});

module.exports.s2t = function(txt, cb){
    var params = {
        model: 'en-US_BroadbandModel',
        content_type: 'audio/flac',
        'interim_results': true,
        'max_alternatives': 3,
        'word_confidence': false,
        timestamps: false,
        keywords: ['colorado', 'tornado', 'tornadoes'],
        'keywords_threshold': 0.5
    };
    // Create the stream.
    var recognizeStream = speech_to_text.createRecognizeStream(params);

    // Pipe in the audio.
    fs.createReadStream('audio-file.flac').pipe(recognizeStream);

    // Get strings instead of buffers from 'data' events.
    recognizeStream.setEncoding('utf8');

    // Listen for events.
    recognizeStream.on('results', function(event) { onEvent('Results:', event); });
    recognizeStream.on('data', function(event) { onEvent('Data:', event); });
    recognizeStream.on('error', function(event) { onEvent('Error:', event); });
    recognizeStream.on('close', function(event) { onEvent(true, event); });
    recognizeStream.on('speaker_labels', function(event) { onEvent('Speaker_Labels:', event); });

    // Displays events on the console.
    var obj = "";
    function onEvent(name, event) {
        //console.log(name, JSON.stringify(event, null, 2));
        if (name === true){
            console.log(obj);
            cb(null, obj);
        }else{
            obj = event;
        }
    };    
}`
