### ISSUE TITLE
Issue runnng pip3 install --upgrade watson-developer-cloud

### ISSUE THREAD

**Issue by rgjones33** [watson-developer-cloud/python-sdk#475]
#### Expected behavior
Successful install

#### Actual behavior
```GMBP:bin rgjones$ pip3 install --upgrade watson-developer-cloud
Collecting watson-developer-cloud
  Using cached https://files.pythonhosted.org/packages/4f/b5/d2242076082287db54ba04b435cf288b0fd03e767faf34df70d809cec404/watson-developer-cloud-1.3.3.tar.gz
Requirement not upgraded as not directly required: requests<3.0,>=2.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from watson-developer-cloud) (2.18.4)
Collecting python_dateutil>=2.5.3 (from watson-developer-cloud)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting autobahn>=0.10.9 (from watson-developer-cloud)
  Using cached https://files.pythonhosted.org/packages/1b/92/5753b2123802a81bda4a9cf759732dfab21baffb3bfcdac725e097df39df/autobahn-18.5.1-py2.py3-none-any.whl
Collecting Twisted>=13.2.0 (from watson-developer-cloud)
  Using cached https://files.pythonhosted.org/packages/12/2a/e9e4fb2e6b2f7a75577e0614926819a472934b0b85f205ba5d5d2add54d0/Twisted-18.4.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/incremental/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    No local packages or working download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q7/9rf0szzj13j2msj0lnfslh_m0000gn/T/pip-install-gemz3jnq/Twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')
```
#### Steps to reproduce the problem
Using Python.org 3.5.4
pip3 install --upgrade watson-developer-cloud

#### python sdk version
?
#### python version
3.5.4

**Comment by ehdsouza** [comment]
HI @rgjones33,

Is your company under a proxy?

**Comment by rgjones33** [comment]
Hi I work for IBM. I was able to install watson_developer_cloud using Python 3.6.5. Seems to be an issue with older version of ssl in previous python versions. I originally installed 3.5 for other reasons.

**Comment by ehdsouza** [comment]
Could you upgrade your pip version and try:
```
pip install --upgrade pip
```

**Comment by rgjones33** [comment]
Yes I had tried upgrading to the latest pip3. At this point I am working with Python 3.6.5. We can close this issue if you do not plan to support older version of Python.

**Comment by ehdsouza** [comment]
Closing this as you could succeed with python 3.6.5. I tried with a 3.5 on my Mac and it worked fine. Reopen if you need any additional help
