### ISSUE TITLE
Issue: builtins.KeyError: 'results' when running example code with speakers_label = True

### ISSUE THREAD

**Issue by liuzheqi0723** [watson-developer-cloud/python-sdk#489]
#### Expected behavior
I was trying to generate speech to text with different speakers labels.
#### Actual behavior
Python actually gives me KeyError after generating the text results and no labels show up
#### Steps to reproduce the problem
I basically added speaker_labels = True in examples/speech_to_text_v1.py line 57.
#### Code snippet (Note: Do not paste your credentials)
```python
with open(join(ROOT_DIR, 'recordings/0001.wav'),
          'rb') as audio_file:
    speech_to_text.recognize_with_websocket(
        audio=audio_file, recognize_callback=mycallback, speaker_labels = True)
```

error:
```
[{'transcript': 'several tornadoes touch down as a line of severe thunderstorms swept through Colorado on Sunday '}]
several tornadoes touch down as a line of severe thunderstorms swept through Colorado on Sunday
Unhandled Error
Traceback (most recent call last):
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1553, in processData
    fr = self.onFrameEnd()
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1675, in onFrameEnd
    self._onMessageEnd()
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 159, in _onMessageEnd
    self.onMessageEnd()
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "/Users/zheqiliu/anaconda3/lib/python3.6/site-packages/watson_developer_cloud/websocket/speech_to_text_websocket_listener.py", line 132, in onMessage
    if json_object['results']:
builtins.KeyError: 'results'
```
#### python sdk version
sdk: 1.3.5
#### python version
python 3.6.4

**Comment by ehdsouza** [comment]
HI,

This is currently a bug where we parse the data returned from the service and don't really return the entire json from the service. A new method would be added in the upcoming to the callback to handle returning of unparsed data.

**Comment by germanattanasio** [comment]
Was this fixed in the last release @ehdsouza ?

**Comment by ehdsouza** [comment]
Sorry forgot to update about the release here.
`on_data()` should return the unparsed data. For more information check the changelog for version  1.4.0: https://github.com/watson-developer-cloud/python-sdk/wiki/Changelog#version-140
