### ISSUE TITLE
Exception passing `ToneInput` object to `tone_analyzer.tone`

### ISSUE THREAD

**Issue by smithsz** [watson-developer-cloud/python-sdk#495]
#### Expected behavior
Below script to run without error:
```py
from __future__ import print_function

from watson_developer_cloud import ToneAnalyzerV3
from watson_developer_cloud.tone_analyzer_v3 import ToneInput

tone_analyzer = ToneAnalyzerV3(
    username='xxxxxx',
    password='xxxxxx',
    version='2017-09-26')

ti = ToneInput('I am very happy. It is a good day.')
print(tone_analyzer.tone(
    tone_input=ti,
    content_type="application/json"))  # TypeError: 'ToneInput' object is not iterable
```
#### Actual behavior
Raises following exception:
```
Traceback (most recent call last):
  File "/Users/samsmith/tmp/python-sdk-test/main.py", line 51, in <module>
    content_type="application/json"))  # TypeError: 'ToneInput' object is not iterable
  File "/Users/samsmith/.virtualenvs/python-sdk-test/lib/python2.7/site-packages/watson_developer_cloud/tone_analyzer_v3.py", line 175, in tone
    accept_json=True)
  File "/Users/samsmith/.virtualenvs/python-sdk-test/lib/python2.7/site-packages/watson_developer_cloud/watson_service.py", line 434, in request
    **kwargs)
  File "/Users/samsmith/.virtualenvs/python-sdk-test/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/samsmith/.virtualenvs/python-sdk-test/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/samsmith/.virtualenvs/python-sdk-test/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/samsmith/.virtualenvs/python-sdk-test/lib/python2.7/site-packages/requests/adapters.py", line 460, in send
    for i in request.body:
TypeError: 'ToneInput' object is not iterable
```

#### python sdk version
`watson-developer-cloud==1.3.5`

#### python version
Python 2.7

**Comment by smithsz** [comment]
I'm wondering if the `ToneInput` model should inherit from `dict`? This works as long as all the attributes required in the JSON are `set` in the dictionary.

Failing that, we could use the `_to_dict` method when constructing the request payload in `WatsonService.request`?

**Comment by germanattanasio** [comment]
@ehdsouza here is more context https://ibm-watson.slack.com/archives/C4XC6SWKG/p1529331757000625
