### ISSUE TITLE
Visual_recognition_v3 detect_faces method broken when calling with url parameter

### ISSUE THREAD

**Issue by j-rachit** [watson-developer-cloud/python-sdk#497]
#### Expected behavior
Expected behaviour when calling the method with url parameter is to produce an output from the server like the classify method.
#### Actual behavior
Instead, the following exception is encountered:
```
Traceback (most recent call last):
  File "C:/Users/<path to my file, hidden for privacy>", line 50, in <module>
    faces_result = visual_recognition.detect_faces(parameters=json.dumps({'url': test_url}))
  File "C:\Python27\lib\site-packages\watson_developer_cloud\visual_recognition_v3.py", line 233, in detect_faces
    accept_json=True)
  File "C:\Python27\lib\site-packages\watson_developer_cloud\watson_service.py", line 463, in request
    info=error_info, httpResponse=response)
WatsonApiException: Error: No images were specified., Code: 400 , X-dp-watson-tran-id: gateway01-283560373 , X-global-transaction-id: 7ecac92c5b2e650710e6c9b5
```
#### Steps to reproduce the problem
It is possible to call the detect_faces procedure with the url parameter instead of a file, or execute the example given in the repository.
#### Code snippet (Note: Do not paste your credentials)
Taken from the example posted in the repository,
```python
#works as expected 
url_result = visual_recognition.classify(parameters=json.dumps({'url': test_url}))
print(json.dumps(url_result, indent=2))

#fails with exception  
faces_result = visual_recognition.detect_faces(parameters=json.dumps({'url': test_url}))
print(json.dumps(faces_result, indent=2))
```
#### python sdk version
1.4.0
#### python version
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32

**Comment by ehdsouza** [comment]
Hi, what is the value of your `test_url`. I could run the example without any issue

**Comment by ehdsouza** [comment]
It seems more like your environment issue in windows. Could you try escaping the backslash in the url.

**Comment by berinhard** [comment]
I'am a +1 with this issue. Here's the example:

```python
>>> url
'https://bienal-image-analyser.s3.amazonaws.com/base/DSC_0027.JPG'
>>> result = visual_recognition.classify(url=url)
>>> result['images_processed']
1
>>> faces = visual_recognition.detect_faces(url=url)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    faces = visual_recognition.detect_faces(url=url)
  File "/home/bernardo/.virtualenvs/bienal-art-analyser/lib/python3.6/site-packages/watson_developer_cloud/visual_recognition_v3.py", line 225, in detect_faces
    accept_json=True)
  File "/home/bernardo/.virtualenvs/bienal-art-analyser/lib/python3.6/site-packages/watson_developer_cloud/watson_service.py", line 472, in request
    info=error_info, httpResponse=response)
watson_developer_cloud.watson_service.WatsonApiException: Error: No images were specified., Code: 400 , X-dp-watson-tran-id: gateway01-119976319 , X-global-transaction-id: 7ecac92c5b5f938f0726b17f
```

**Python SDK version**: 1.5.0
**Python version**: 3.6.5

**Comment by germanattanasio** [comment]
I just tried 
```
curl -u "apikey:{apikey}" "https://gateway.watsonplatform.net/visual-recognition/api/v3/detect_faces?url=https://bienal-image-analyser.s3.amazonaws.com/base/DSC_0027.JPG&version=2018-03-19"
```

And got back

```json
{
  "images": [{
    "faces": [],
    "source_url": "https://bienal-image-analyser.s3.amazonaws.com/base/DSC_0027.JPG",
    "resolved_url": "https://bienal-image-analyser.s3.amazonaws.com/base/DSC_0027.JPG"
  }],
  "images_processed": 1
}
```

**Comment by berinhard** [comment]
Thanks @germanattanasio, I tested it locally and it works indeed. But is there a reason not working with in the Python SDK?
