### ISSUE TITLE
Dict comprehension incompatible with python 2.6

### ISSUE THREAD

**Issue by ghost** [watson-developer-cloud/python-sdk#51]
Import statement results in the following exception:

`Traceback (most recent call last):
  File "/home/chakravr/workspaces/bluegoat-experimental/bluegoat-raas-experimental/chakravr-experiments/src/main/scripts/bluemix_scripts/run_raas_csf_experiment.py", line 15, in <module>
    from watson_developer_cloud import RetrieveAndRankV1, WatsonException
  File "/usr/lib/python2.6/site-packages/watson_developer_cloud/__init__.py", line 15, in <module>
    from .watson_developer_cloud_service import WatsonDeveloperCloudService
  File "/usr/lib/python2.6/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 52
    return {k: v for k, v in dictionary.items() if v is not None}
                   ^
SyntaxError: invalid syntax`

Syntax appears to be incompatible with python 2.6: http://stackoverflow.com/questions/1747817/create-a-dictionary-with-list-comprehension-in-python.  Works fine with python 2.7

**Comment by jsstylos** [comment]
Thanks for the report. There's currently a bug where the library is not being tested against 2.6. I'll check to see if there are any other compatibility issues preventing 2.6 support.

**Comment by jsstylos** [comment]
Fixed to support -- and test -- Python 2.6 in 302c9b588610536ec99f6c6673799c3d68789cdb
