### ISSUE TITLE
Error in python using speech_to_text websocket when using a recognize_callback, interim_results and speaker_labels

### ISSUE THREAD

**Issue by Peamon** [watson-developer-cloud/python-sdk#539]
#### Expected behavior
Getting json result

#### Actual behavior
2 Hunhandled Errors

```
Unhandled Error
Traceback (most recent call last):
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1553, in processData
    fr = self.onFrameEnd()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1675, in onFrameEnd
    self._onMessageEnd()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 159, in _onMessageEnd
    self.onMessageEnd()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/watson_developer_cloud/websocket/speech_to_text_websocket_listener.py", line 132, in onMessage
    if json_object['results']:
builtins.KeyError: 'results'

Unhandled Error
Traceback (most recent call last):
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/watson_developer_cloud/websocket/speech_to_text_websocket_listener.py", line 47, in __init__
    reactor.run() # pylint: disable=E1101
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/base.py", line 1261, in run
    self.mainLoop()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/base.py", line 1273, in mainLoop
    self.doIteration(t)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/tcp.py", line 519, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/protocols/tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1545, in processData
    fr = self.onFrameData(payload)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1640, in onFrameData
    self._onMessageFrameData(payload)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 150, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "/home/clarte/miniconda3/envs/track/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 601, in onMessageFrameData
    self.frame_data.append(payload)
builtins.AttributeError: 'NoneType' object has no attribute 'append'

```
#### Steps to reproduce the problem
Follow the tutorial in python, add interim_results and speaker_labels options

#### Code snippet (Note: Do not paste your credentials)
```
from watson_developer_cloud import SpeechToTextV1, ToneAnalyzerV3
from watson_developer_cloud.websocket import RecognizeCallback
import json

class MyRecognizeCallback(RecognizeCallback):
    def __init__(self):
        RecognizeCallback.__init__(self)

    def on_data(self, data):
        print(json.dumps(data, indent=2))

    def on_error(self, error):
        print('Error received: {}'.format(error))

    def on_inactivity_timeout(self, error):
        print('Inactivity timeout: {}'.format(error))

speech_to_text = SpeechToTextV1(...)

myRecognizeCallback = MyRecognizeCallback()

with open(..., 'rb') as audio_file:
    speech_to_text.recognize_using_websocket(
        audio=audio_file,
        content_type='audio/flac',
        model='en-US_BroadbandModel',
        recognize_callback=myRecognizeCallback,
        interim_results=True,
        speaker_labels=True)

```
#### python sdk version
watson-developer-cloud   1.6.0

#### python version
Python 3.5.5 :: Anaconda, Inc.

### proposed solution
In speech_to_text_websocket_listener.py

line 129 to 132:
```
            elif 'results' in json_object or 'speaker_labels' in json_object:
                hypothesis = ''
                # empty hypothesis
                if json_object['results']:
```

changed to :
```
            elif 'results' in json_object or 'speaker_labels' in json_object:
                hypothesis = ''
                # empty hypothesis
                if 'results' in json_object:
```

And line 142 &143, call 'on_data' even if result not in json_object.
```
                    self.callback.on_transcription(transcripts)
                    self.callback.on_data(json_object)
```
To
```
                    self.callback.on_transcription(transcripts)
                self.callback.on_data(json_object)
```

**Comment by germanattanasio** [comment]
@Peamon do you think you can write a PR? It looks like you how to fix this.

On the other hand, we are moving to use a new WebSocket library because we found that autoban has a lot of issues with python 3.x We hope to have that ready by next week.
