### ISSUE TITLE
websocket import error (websocket-client seems missing in setup.py)

### ISSUE THREAD

**Issue by papachoco** [watson-developer-cloud/python-sdk#557]
#### Expected behavior
I am getting an import error when doing
```
from watson_developer_cloud import websocket
```
#### Actual behavior
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/watson_developer_cloud-2.0.0-py2.7.egg/watson_developer_cloud/__init__.py", line 32, in <module>
    from .speech_to_text_v1_adapter import SpeechToTextV1Adapter as SpeechToTextV1
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/watson_developer_cloud-2.0.0-py2.7.egg/watson_developer_cloud/speech_to_text_v1_adapter.py", line 1, in <module>
    from watson_developer_cloud.websocket import RecognizeCallback, RecognizeListener, AudioSource
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/watson_developer_cloud-2.0.0-py2.7.egg/watson_developer_cloud/websocket/__init__.py", line 18, in <module>
    from .recognize_listener import RecognizeListener
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/watson_developer_cloud-2.0.0-py2.7.egg/watson_developer_cloud/websocket/recognize_listener.py", line 17, in <module>
    import websocket
ImportError: No module named websocket
```
#### python sdk version
watson_developer_cloud-2.0.0

#### python version
2.7

Carlos

**Comment by ehdsouza** [comment]
Thanks for this!
