### ISSUE TITLE
Unnauthorized: Access is denied due to invalid Creditionals/API

### ISSUE THREAD

**Issue by yashpatel001** [watson-developer-cloud/python-sdk#567]
#### Expected behavior
Tone Detection

#### Actual behavior
```
user@user-Latitude-E5420:~/Downloads/python-sdk-master/examples/conversation_tone_analyzer_integration$ python tone_conversation_integration.v1.py 
Traceback (most recent call last):
  File "tone_conversation_integration.v1.py", line 72, in <module>
    invokeToneConversation(global_payload, global_maintainToneHistoryInContext)
  File "tone_conversation_integration.v1.py", line 62, in invokeToneConversation
    tone = tone_analyzer.tone(tone_input=payload['input']['text'], content_type='application/json').get_result()
  File "/home/user/.local/lib/python2.7/site-packages/watson_developer_cloud/tone_analyzer_v3.py", line 198, in tone
    accept_json=True)
  File "/home/user/.local/lib/python2.7/site-packages/watson_developer_cloud/watson_service.py", line 468, in request
    info=error_info, httpResponse=response)
watson_developer_cloud.watson_service.WatsonApiException: Error: Unauthorized: Access is denied due to invalid credentials , Code: 401 , X-dp-watson-tran-id: gateway02-251661447 , X-global-transaction-id: ffea405d5ba345e80f000c87
```
#### Code snippet (Note: Do not paste your credentials)
```py
from __future__ import print_function
import json
import os
from dotenv import load_dotenv, find_dotenv

from watson_developer_cloud import ConversationV1
from watson_developer_cloud import ToneAnalyzerV3
from watson_developer_cloud.tone_analyzer_v3 import ToneInput

# import tone detection
import tone_detection

# load the .env file containing your environment variables for the required
# services (conversation and tone)
load_dotenv(find_dotenv())

# replace with your own conversation credentials or put them in a .env file
conversation = ConversationV1(
    username=os.environ.get('CONVERSATION_USERNAME') or 'YOUR SERVICE NAME',
    password=os.environ.get('CONVERSATION_PASSWORD') or 'YOUR PASSWORD',
    version='2017-12-13')

# replace with your own tone analyzer credentials
tone_analyzer = ToneAnalyzerV3(
    username=os.environ.get('TONE_ANALYZER_USERNAME') or 'YOUR SERVICE NAME',
    password=os.environ.get('TONE_ANALYZER_PASSWORD') or 'YOUR SERVICE NAME',
    version='2018-09-19')

# replace with your own workspace_id
workspace_id = os.environ.get('WORKSPACE_ID') or 'YOUR WORKSPACE ID'

# This example stores tone for each user utterance in conversation context.
# Change this to false, if you do not want to maintain history
global_maintainToneHistoryInContext = True

# Payload for the Watson Conversation Service
# user input text required - replace "I am happy" with user input text.
global_payload = {
    'workspace_id': workspace_id,
    'input': {
        'text': "I am happy"
    }
}


def invokeToneConversation(payload, maintainToneHistoryInContext):
    """
     invokeToneConversation calls the Tone Analyzer service to get the
     tone information for the user's input text (input['text'] in the payload
     json object), adds/updates the user's tone in the payload's context,
     and sends the payload to the
     conversation service to get a response which is printed to screen.
     :param payload: a json object containing the basic information needed to
     converse with the Conversation Service's message endpoint.
     :param maintainHistoryInContext:


     Note: as indicated below, the console.log statements can be replaced
     with application-specific code to process the err or data object
     returned by the Conversation Service.
    """
    tone = tone_analyzer.tone(tone_input=payload['input']['text'], content_type='application/json').get_result()
    conversation_payload = tone_detection.\
        updateUserTone(payload, tone, maintainToneHistoryInContext)
    response = conversation.message(workspace_id=workspace_id,
                                    input=conversation_payload['input'],
                                    context=conversation_payload['context']).get_result()
    print(json.dumps(response, indent=2))


# synchronous call to conversation with tone included in the context
invokeToneConversation(global_payload, global_maintainToneHistoryInContext)
```
#### python sdk version
 watson-developer-cloud==1.6.0
#### python version
2.6

Note : we verify credentials 5-6 Times , i think no issue in credentials

**Comment by ehdsouza** [comment]
@yashpatel001 are you using CF instance? If then you have to user `username` and `password`. If you are using RC instance, then pass in `iam_apikey`.

**Comment by yashpatel001** [comment]
@ehdsouza  In code You are not passing any URL and i am using us_south region so no need iam_apikey.

Try to help to solve above issue

**Comment by yashpatel001** [comment]
Traceback (most recent call last):
  File "tone_conversation_integration.v1.py", line 72, in <module>
    invokeToneConversation(global_payload, global_maintainToneHistoryInContext)
  File "tone_conversation_integration.v1.py", line 62, in invokeToneConversation
    tone = tone_analyzer.tone(tone_input=payload['input']['text'], content_type='application/json').get_result()
  File "/home/user/.local/lib/python2.7/site-packages/watson_developer_cloud/tone_analyzer_v3.py", line 198, in tone
    accept_json=True)
  File "/home/user/.local/lib/python2.7/site-packages/watson_developer_cloud/watson_service.py", line 468, in request
    info=error_info, httpResponse=response)
watson_developer_cloud.watson_service.WatsonApiException: Error: Unauthorized: Access is denied due to invalid credentials , Code: 401 , X-dp-watson-tran-id: gateway02-1266248249 , X-global-transaction-id: ffea405d5ba88ae64b796a39

**Comment by yashpatel001** [comment]
i found issue is in this function "invokeToneConversation(payload, maintainToneHistoryInContext):"
tone_analyzer api problem
Inside invokeToneConversation function if we write we are getting
tone_input = ToneInput('I am very much hungry.')
tone = service.tone(tone_input=tone_input, content_type="application/json")
but if we pass payload['input']['text'] instead of string error coming please try to solve  invokeToneConversation() and give which watson python sdk will support

**Comment by germanattanasio** [comment]
The sample code should work. Please make sure you are using service instances from US South. You will see the service url to be like: `https://gateway.watsonplatform.net`. Otherwise you need to specify the url along with the credentials.


```py
tone_analyzer = ToneAnalyzerV3(
    username=os.environ.get('TONE_ANALYZER_USERNAME') or 'YOUR SERVICE NAME',
    password=os.environ.get('TONE_ANALYZER_PASSWORD') or 'YOUR SERVICE NAME',
    url="REPLACE THE URL HERE"
    version='2018-09-19'
)
```

**Comment by germanattanasio** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs.
Check the CONTRIBUTING.md for an example.
