### ISSUE TITLE
R&R Python method create_config does not work

### ISSUE THREAD

**Issue by scot-taylor-ibm** [watson-developer-cloud/python-sdk#59]
I've managed to create, list, check the status of, delete, and recreate a Solr cluster. Now I can't upload the sample config:
```
>>> newconfig = retrieve_and_rank.create_config("scba5dcf95_c354_4c14_822e_00fe40f85ed9", "example_config", "/Users/taylorscot/python-sdk/resources/solr_config.zip")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "watson_developer_cloud/retrieve_and_rank_v1.py", line 53, in create_config
    files={'body': config}, headers={'content-type': 'application/zip'}, accept_json=True)
  File "watson_developer_cloud/watson_developer_cloud_service.py", line 253, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Unknown error
```

```
>>> os.getcwd()
'/Users/taylorscot/python-sdk'
>>> newfile = "./resources/solr_config.zip"
>>> newconfig = retrieve_and_rank.create_config("scba5dcf95_c354_4c14_822e_00fe40f85ed9", "example_config", newfile)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "watson_developer_cloud/retrieve_and_rank_v1.py", line 53, in create_config
    files={'body': config}, headers={'content-type': 'application/zip'}, accept_json=True)
  File "watson_developer_cloud/watson_developer_cloud_service.py", line 253, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Unknown error
```
The watson_developer_cloud/retrieve_and_rank_v1.py file has this comment:
```
# Need to test
    def create_config(self, solr_cluster_id, config_name, config):
        return self.request(method='POST', url='/v1/solr_clusters/{0}/config/{1\
}'.format(solr_cluster_id, config_name),
                            files={'body': config}, headers={'content-type': 'a\
pplication/zip'}, accept_json=True)
```

Any idea when the testing and/or a fix might happen? Thanks.

**Comment by jsstylos** [comment]
I have done some testing on the method -- the latest version of the Python SDK should give you a slightly more verbose error -- my guess is "Unknown error, Code: 409", if a config with that name already exists.

**Comment by jsstylos** [comment]
@scot-taylor-ibm: Can you verify that the latest version gives a sensible error message?

**Comment by scot-taylor-ibm** [comment]
@jsstylos: I pulled the latest python-sdk, reran the test, and got essentially the same results with the addition of a Code 400:
```
>>> config_upload = retrieve_and_rank.create_config('sce94ccf57_1ee8_410b_8e67_3b2b3311a994', 'test_config', '/Users/taylorscot/python-sdk/resources/solr_config.zip')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "watson_developer_cloud/retrieve_and_rank_v1.py", line 53, in create_config
    files={'body': config}, headers={'content-type': 'application/zip'}, accept_json=True)
  File "watson_developer_cloud/watson_developer_cloud_service.py", line 253, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Unknown error, **Code: 400**
>>> config_upload.__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'config_upload' is not defined
>>>
```

**Comment by jsstylos** [comment]
The config is being passed as a string with the filename in it here -- it should be passed as a file object. I improved the error reporting (again) for solr messages, which should appear in the next release.

**Comment by scot-taylor-ibm** [comment]
Leaving this here so it's recorded somewhere other than Slack:
```
>>> with open('/Users/taylorscot/python-sdk/resources/solr_config.zip', 'rb') as config:
...   config_status = retrieve_and_rank.create_config('sce94ccf57_1ee8_410b_8e67_3b2b3311a994', 'test_config', config)
...   print(json.dumps(config_status, indent=2))
...
{
  "message": "WRRCSR026: Successfully uploaded named config [test_config] for Solr cluster [sce94ccf57_1ee8_410b_8e67_3b2b3311a994].",
  "statusCode": 200
}
```
