### ISSUE TITLE
IAM / VCAP_SERVICES / Blank constructor leads to  "You must specify your IAM api key" error.

### ISSUE THREAD

**Issue by ishida330** [watson-developer-cloud/python-sdk#593]
#### Expected behavior
The doc says:
>"If you run your app in IBM Cloud, the SDK gets credentials from the VCAP_SERVICES environment variable."

So if all these conditions are met:
1) The app is bound to the Watson service in IBM Cloud( VCAP_SERVICES exists)
2) IAM Auth = "apikey" will be used
3) "apikey" was NOT set in the constructor like this.
var AssistantV1 = require('watson-developer-cloud/assistant/v1');
var assistant = new AssistantV1({
    version: '2018-09-20'
});

Then ==> "apikey" was extracted from VCAP_SERVICES automatically and the request works.

#### Actual behavior
Got the following error .
Traceback (most recent call last):
  File "a02_no_apikey.py", line 30, in <module>
    version='2018-09-20'
  File "C:\PROGRAMDATA\MINICONDA3\lib\site-packages\watson_developer_cloud\assistant_v1.py", line 100, in __init__
    use_vcap_services=True)
  File "C:\PROGRAMDATA\MINICONDA3\lib\site-packages\watson_developer_cloud\watson_service.py", line 278, in __init__
    'You must specify your IAM api key or username and password service '
**ValueError: You must specify your IAM api key or username and password service credentials (Note: these are different from your Bluemix id)**

I think "watson_service.py" line 265-266 should be
`
                if 'apikey' in self.vcap_service_credentials:
                    self.set_iam_apikey(self.vcap_service_credentials.get('apikey'))
`
NOT
`                if 'iam_apikey' in self.vcap_service_credentials:
                    self.set_iam_apikey(self.vcap_service_credentials.get('iam_apikey'))
`
as the entry in VCAP_SERVICES is "apikey", Not "iam_apikey".

            "credentials": {
                "apikey": "xxxxxx...xxx",
                "iam_apikey_description": ...
                "url": "https://gateway-syd.watsonplatform.net/assistant/api"
            },

( "iam_apikey" is correct name in the constructor, but not for VCAP_SERVICES. Confusing.. )

#### python sdk version
2.4.0

**Comment by ishida330** [comment]
Thanks for the quick fix. Now it worked fine !
