### ISSUE TITLE
Issues with Python SDK in function "assistant.update_workspace"

### ISSUE THREAD

**Issue by donovat** [watson-developer-cloud/python-sdk#669]
Describe the bug
When using the Python SDK and the function "assistant.update_workspace" (v1) calls, to upload a new JSON workspace, it crashes with an error due to incorrectly formatted "Search skill" rich response.

To Reproduce

    In Premium or Plus Assistant Instance, create an new dialog skill.
    Add a few dialog nodes, making sure that one of the dialog nodes includes the "Search Skill" rich response type. - Include as the query parameter.
    Save and exit dialog skill.
    Export / download the resulting workspace skill JSON file to your pc.
    Using a python application which includes the function assistant.update_workspace to push the just saved JSON file back to the dialog skill.
    Error given:
    watson_developer_cloud.watson_service.WatsonApiException: Error: Invalid Request Body, Code: 400 , Information: {u'errors': [{u'path': u'.dialog_nodes[6105].output.generic[0]', u'message': u'must contain query when response_type is search_skill'}, {u'path': u'.dialog_nodes[6105].output.generic[0]', u'message': u'must contain query_type when response_type is search_skill'}]} , X-dp-watson-tran-id: 6294489336d063789092ed1a29af4005 , X-global-transaction-id: 6294489336d063789092ed1a29af4005

If you remove the search skill output response element i.e. output {}
and try again, upload works fine.

**Note: This issue was originally opened in github (under assistant ) #26265**
[https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/26265](https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/26265)

Also note, tested with latest SDK and get the following error:
Pushing to the TARGET WS...
Traceback (most recent call last):
File "deploy_workspace-both_TEST_and_LIVE-ibm_watson-sdk.py", line 254, in
response = assistant_TARGET.update_workspace(workspace_id = workspace_id, name=data['name'], description=data['description'], language=data['language'], intents=data['intents'], entities=data['entities'], dialog_nodes=data['dialog_nodes'], counterexamples=data['counterexamples'], metadata=data['metadata'])
File "/Users/timd/Developments/Arthritis_Research_UK_dev/Deploy_WS_to_Prod/ibm_watson/assistant_v1.py", line 527, in update_workspace
accept_json=True)
File "/Library/Python/2.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 358, in request
raise ApiException(response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: must contain query when response_type is search_skill, Code: 400 , X-global-transaction-id: 7674f8e186faa35621bb062eb53a9157

**Comment by donovat** [comment]
using curl I get the following;
curl -S -H "Content-Type: application/json" -X POST -u "apikey:IKK8tN-XYF4IZ9dP599tO1DMq0psxxxxxxxxxxxxxx" -d "{"name":"ARUK-BETA-V7-Test","intents":[],"entities":[],"language":"en","description":"Example workspace updated via API.","dialog_nodes": [{"type": "standard","title": "Welcome","output": {"generic": [{"query": "","filter": "","query_type": "natural_language","response_type": "search_skill"}]},"conditions": "welcome","dialog_node": "node_2_1550250010528"},{"type":"standard","title":"debug MSG-->discovery-tim","output": {"generic": [{"query": "","filter": "","query_type": "natural_language","response_type": "search_skill"}]},"parent": "node_2_1550250010528","metadata": {},"conditions": "true","dialog_node":"node_2_1558018688756"}]}" "https://gateway-lon.watsonplatform.net/assistant/api/v1/workspaces/808683ab-774d-4a10-8696-3c650f8c5261?version=2019-02-28"

response === {"name":"ARUK-BETA-V7-Test","language":"en","metadata":{"api_version":{"major_version":"v1","minor_version":"2019-02-28"}},"description":"Example workspace updated via API.","workspace_id":"808683ab-774d-4a10-8696-3c650f8c5261","learning_opt_out":true}

so the only issue is via the python sdk.

**Comment by ehdsouza** [comment]
@donovat thanks for creating this issue.

Right now the search skill is in beta and would not be supported by the SDK as the API definitions from which the SDKs are created are not updated as yet.

**Comment by donovat** [comment]
Hi @ehdsouza - I can understand that the Search Skill is still in Beta, however we need to be able to use the API calls to update the workspaces. Also if I remember right we can fool the API call. If we add just "<? input.text ?>" - it fails, but if we change this to "Here is the questions, <? input.text ?>" - it worked. As it take this as being a string, the first it did not. 

Anyway I take it that this will be fixed by the time search skills are standard?

**Comment by ehdsouza** [comment]
@donovat the search skill is still beta and we expect to have it out in the next release

**Comment by mediumTaj** [comment]
@ehdsouza was this resolved?

**Comment by ehdsouza** [comment]
This will be resolved in the major release or candidate release https://pypi.org/project/ibm-watson/4.0.0rc1/

**Comment by ehdsouza** [comment]
Hi @donovat , in https://pypi.org/project/ibm-watson/4.0.0/ we dont do the conversion from json to model before making the api call, can you see if your issue is resolved?
