### ISSUE TITLE
Conflict with typing extensions on python3.7

### ISSUE THREAD

**Issue by pslq** [watson-developer-cloud/python-sdk#688]
After upgrade to python 3.7, ibm_watson become unusable due to conflicts with standard typing giving errors like:

-------------------
```
Traceback (most recent call last):
  File "watson_interface.py", line 2, in <module>
    import ibm_watson
  File "/usr/local/lib/python3.7/dist-packages/ibm_watson/__init__.py", line 16, in <module>
    from ibm_cloud_sdk_core import IAMTokenManager, DetailedResponse, BaseService, ApiException
  File "/usr/local/lib/python3.7/dist-packages/ibm_cloud_sdk_core/__init__.py", line 16, in <module>
    from .base_service import BaseService
  File "/usr/local/lib/python3.7/dist-packages/ibm_cloud_sdk_core/base_service.py", line 26, in <module>
    from .iam_token_manager import IAMTokenManager
  File "/usr/local/lib/python3.7/dist-packages/ibm_cloud_sdk_core/iam_token_manager.py", line 17, in <module>
    from .jwt_token_manager import JWTTokenManager
  File "/usr/local/lib/python3.7/dist-packages/ibm_cloud_sdk_core/jwt_token_manager.py", line 17, in <module>
    import jwt
  File "/usr/local/lib/python3.7/dist-packages/jwt/__init__.py", line 19, in <module>
    from .api_jwt import (
  File "/usr/local/lib/python3.7/dist-packages/jwt/api_jwt.py", line 7, in <module>
    from typing import Callable, Dict, List, Optional, Union # NOQA
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
-------------------------------------
```

This can be avoided by removing the typing extension downloaded along with ibm_watson, like shown bellow:
```
$ pip3 uninstall typing
Uninstalling typing-3.7.4.1:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/typing-3.7.4.1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/typing.py
Proceed (y/n)? y
  Successfully uninstalled typing-3.7.4.1
$ python3
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_watson
>>> 
```

Please update the requirements.txt to avoid this conflict on python versions above 
3.6

**Comment by ehdsouza** [comment]
Thanks for the taking the time to create this issue. Could you specify from which version of python you upgraded from?

I created a fresh install of the `ibm_watson` package and don't see any `typing` installed.

```
(myenv) ➜  ~ pip install ibm_watson
Collecting ibm_watson
Collecting requests<3.0,>=2.0 (from ibm_watson)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting ibm-cloud-sdk-core>=0.5.1 (from ibm_watson)
Collecting python-dateutil>=2.5.3 (from ibm_watson)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting websocket-client==0.48.0 (from ibm_watson)
  Using cached https://files.pythonhosted.org/packages/8a/a1/72ef9aa26cfe1a75cee09fc1957e4723add9de098c15719416a1ee89386b/websocket_client-0.48.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0,>=2.0->ibm_watson)
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0,>=2.0->ibm_watson)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests<3.0,>=2.0->ibm_watson)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests<3.0,>=2.0->ibm_watson)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting PyJWT>=1.7.1 (from ibm-cloud-sdk-core>=0.5.1->ibm_watson)
  Using cached https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.5.3->ibm_watson)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: certifi, chardet, urllib3, idna, requests, PyJWT, six, python-dateutil, ibm-cloud-sdk-core, websocket-client, ibm-watson
Successfully installed PyJWT-1.7.1 certifi-2019.6.16 chardet-3.0.4 ibm-cloud-sdk-core-0.5.1 ibm-watson-3.4.0 idna-2.8 python-dateutil-2.8.0 requests-2.22.0 six-1.12.0 urllib3-1.25.3 websocket-client-0.48.0
(myenv) ➜  ~ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_watson
>>>
```
