### ISSUE TITLE
Python API doesn't seem to do anything except throw an error

### ISSUE THREAD

**Issue by AverageGuy** [watson-developer-cloud/python-sdk#691]
---

**Overview**
Curl works just fine, at least to produce an audio file:

`curl -X POST -u "apikey:REDACTED"\
--header "Content-Type: application/json" \
--header "Accept: audio/wav" \
--data "{\"text\":\"Hello world\"}" \
--output open.wav \
"https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize"`
 **Check service status**

However the following script doesn't:
`from ibm_watson import TextToSpeechV1
import json

text_to_speech = TextToSpeechV1(
    iam_apikey='REDACTED',
    url='https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize'
)

with open('hello_world.wav', 'wb') as audio_file:
    audio_file.write(
        text_to_speech.synthesize(
            'Hello world',
            voice='en-US_AllisonVoice',
            accept='audio/wav'        
        ).get_result().content)

`
When I run it I get:
`Traceback (most recent call last):
  File "watson.py", line 15, in <module>
    accept='audio/wav'        
  File "/usr/local/lib/python3.5/dist-packages/ibm_watson/text_to_speech_v1.py", line 316, in synthesize
    accept_json=False)
  File "/usr/local/lib/python3.5/dist-packages/ibm_cloud_sdk_core/base_service.py", line 413, in request
    raise ApiException(response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: No such child resource., Code: 404 , X-global-transaction-id: 6b919cec797a950fe4deca7908d172c2
`
**Expected behavior**
I expected to see a response.
**Actual behavior**
See above
**How to reproduce**
See above
**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
sudo pip3 install --upgrade "ibm-watson>=3.4.0"
**Additional information:**
- OS: Ubuntu 16.04 and Raspbian 10
- Which version of `Python` are you using?
3.5 and 3.7.  I have tried it on both system.
**Additional context**
I attempted to run a couple of other scripts that are documented at https://cloud.ibm.com/apidocs/text-to-speech?code=python#get-a-voice
`
voice = text_to_speech.get_voice('en-US_AllisonVoice').get_result()
print(json.dumps(voice, indent=2))

voices = text_to_speech.list_voices().get_result()
print(json.dumps(voices, indent=2))`

They both receive very similar errors.No such child resource., Code: 404

**Comment by AverageGuy** [comment]
Sorry the code quoting doesn't seem to be working or I screwed it up somehow.  I suspect you can see the problem however.

**Comment by AverageGuy** [comment]
I realized that I was using the wrong url.  I just copied it from the curl command and didn't realize it was different.  It should have been https://stream.watsonplatform.net/text-to-speech/api
