### ISSUE TITLE
test_configuration_in_environment raise exception

### ISSUE THREAD

**Issue by zemelLeong** [watson-developer-cloud/python-sdk#717]
```
 Traceback (most recent call last):
   File "F:/PyWorkspace/test_project/test/ibm.py", line 27, in <module>
     res = discovery.test_configuration_in_environment(environment_id=env_id, configuration_id=cfg_id, file=f)
   File "G:\Python36\lib\site-packages\watson_developer_cloud\discovery_v1.py", line 704, in test_configuration_in_environment
     accept_json=True)
   File "G:\Python36\lib\site-packages\watson_developer_cloud\watson_service.py", line 587, in request
     info=error_info, httpResponse=response)
 watson_developer_cloud.watson_service.WatsonApiException: Error: The Preview API was removed on 2019-09-30., Code: 410 , X-dp-watson-tran-id: aa8269d3312b4e5bd7dff72d1fbf9614 , X-global-transaction-id: aa8269d3312b4e5bd7dff72d1fbf9614


``` 
Which API can I change？  
thanks

**Comment by germanattanasio** [comment]
What do you mean by "change" @zemelLeong? The API you are trying to use was deprecated.
You can find more about the methods available for Discovery here: https://cloud.ibm.com/apidocs/discovery/
