### ISSUE TITLE
TTS - synthesize method fails for `Required parameter 'text' is missing.`

### ISSUE THREAD

**Issue by GuyKh** [watson-developer-cloud/python-sdk#798]
**Overview**
Following the example on your documentation - running this code:
```
...
...
    with open('temp.mp3', 'wb') as audio_file:
        audio_file.write(
            service.synthesize(
                    message, accept=output_format, voice=default_voice
                ).get_result().content)
```

**Expected behavior**
This should have created an MP3

**Actual behavior**
Error:
```
Traceback (most recent call last):
  File "/Users/x/workspace/python/watson/watson.py", line 26, in <module>
    main(sys.argv[1:])
  File "/Users/x/workspace/python/watson/watson.py", line 19, in main
    service.synthesize(
  File "/Users/x/workspace/python/watson/env/lib/python3.9/site-packages/ibm_watson/text_to_speech_v1.py", line 332, in synthesize
    response = self.send(request)
  File "/Users/x/workspace/python/watson/env/lib/python3.9/site-packages/ibm_cloud_sdk_core/base_service.py", line 309, in send
    raise ApiException(response.status_code, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Required parameter 'text' is missing., Code: 400 , X-global-transaction-id: 1bb964cf-7cab-4ae1-8d46-c7f95f893ebf
```

**How to reproduce**
```
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
from ibm_watson import TextToSpeechV1

def main(args):
    message = str(args[0])
    print("Saying: " + message)
    authenticator = IAMAuthenticator("<MyAPIKey>")
    service = TextToSpeechV1(authenticator)
    service.set_service_url("http://api.eu-de.text-to-speech.watson.cloud.ibm.com")

    default_voice = "en-US_KevinV3Voice"
    output_format = "audio/mp3"
    service.set_default_headers({"x-watson-learning-opt-out": "true"})


    with open('temp.mp3', 'wb') as audio_file:
        audio_file.write(
            service.synthesize(
                    message, accept=output_format, voice=default_voice
                ).get_result().content)

if __name__ == "__main__":
   main(sys.argv[1:])
```

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
```
ibm-cloud-sdk-core 3.11.0
ibm-watson 5.2.2
``

**Additional information:**
- OS: MacOS, but reproducable also in Ubuntu
- Which version of `Python` are you using? 3.9

**Additional context**
_Add any other details about the problem._

**Comment by apaparazzi0329** [comment]
Hi, @GuyKh. Can you tell me where you found this example?

**Comment by GuyKh** [comment]
@apaparazzi0329 
From the API docs: https://cloud.ibm.com/apidocs/text-to-speech?code=python#synthesize

Copying the full example:
```
from ibm_watson import TextToSpeechV1
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator

authenticator = IAMAuthenticator('{apikey}')
text_to_speech = TextToSpeechV1(
    authenticator=authenticator
)

text_to_speech.set_service_url('{url}')

with open('hello_world.wav', 'wb') as audio_file:
    audio_file.write(
        text_to_speech.synthesize(
            'Hello world',
            voice='en-US_AllisonV3Voice',
            accept='audio/wav'        
        ).get_result().content)
```

**Comment by GuyKh** [comment]
Any news on that @apaparazzi0329?

**Comment by apaparazzi0329** [comment]
Hi @GuyKh, thanks for reminding about this. Unfortunately, I wasn't able to replicate your issue. I copied the exact code from the example and it worked without any edits using the same version of the python-sdk as you are. I tested on Python 3.8.7 and 3.9.2 with the same successful results.

**Comment by apaparazzi0329** [comment]
Are you still getting this same error on your side?

**Comment by GuyKh** [comment]
Hey @apaparazzi0329 - just reproduced this on a new pc:

Again - reproducing the code:
```
    print("Saying: " + message)
    authenticator = IAMAuthenticator("<MyAPIKey>")
    service = TextToSpeechV1(authenticator)
    service.set_service_url("http://api.eu-de.text-to-speech.watson.cloud.ibm.com")

    default_voice = "en-US_KevinV3Voice"
    output_format = "audio/mp3"
    service.set_default_headers({"x-watson-learning-opt-out": "true"})

    print ('about to write the file')
    
    with open('temp.mp3', 'wb') as audio_file:
        audio_file.write(
            service.synthesize(
                    message, accept=output_format, voice=default_voice
                ).get_result().content)
```

**Comment by apaparazzi0329** [comment]
Hmm for some reason the text parameter is dont being passed through even though you are defining it correctly in the `synthesize` method. Try replacing `message` with `text=message` in your synthesize call

**Comment by GuyKh** [comment]
@apaparazzi0329 
Tried that too:

```
...
    with open('temp.mp3', 'wb') as audio_file:
        audio_file.write(
            service.synthesize(
                    text=message, accept=output_format, voice=default_voice
                ).get_result().content)
```

and still getting :
```
  File "watson.py", line 20, in main
    service.synthesize(
  File "C:\Python38\lib\site-packages\ibm_watson\text_to_speech_v1.py", line 343, in synthesize
    response = self.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\ibm_cloud_sdk_core\base_service.py", line 319, in send
    raise ApiException(response.status_code, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Required parameter 'text' is missing., Code: 400 , X-global-transaction-id: cf20db7c-5ee6-4144-895f-5df8caf23633
```

**Comment by apaparazzi0329** [comment]
Ok, can I ask you to do some debugging for me since I cannot recreate this issue. Can you set your service_url to `http://localhost:9000` and then open up a terminal and run `nc -l 9000`; after those steps run your code again. This will allow you to see the request that is being sent by the Watson python-sdk in your terminal. Send that data from your terminal here being sure to black out any api keys that may be revealed

**Comment by apaparazzi0329** [comment]
This will allow me to see if the python sdk is at fault or the TTS service itself

**Comment by GuyKh** [comment]
@apaparazzi0329 

```
POST /v1/synthesize?voice=en-US_KevinV3Voice HTTP/1.1
Host: localhost:9000
User-Agent: watson-apis-python-sdk-5.3.0 Windows 10 3.8.2
Accept-Encoding: gzip, deflate
Accept: audio/mp3
Connection: keep-alive
X-IBMCloud-SDK-Analytics: service_name=text_to_speech;service_version=V1;operation_id=synthesize
content-type: application/json
x-watson-learning-opt-out: true
Authorization: Bearer eyJraWQiOiIyMDIxMDgxOTA4MTciLCJhbGciOiJSUzI1NiJ9.eyJpYW1faWQiOiJpYW0tU2VydmljZUlkLTFhYzAxODc0LTVjMzMtNDdmYy1hM........
Content-Length: 20

{"text": "Hey Mate"}
```

**Comment by GuyKh** [comment]
@apaparazzi0329 

I actually think I've found the issue.
I've noticed that i've been using server `http://api.eu-de.text-to-speech.watson.cloud.ibm.com`
Note -HTTP and not HTTPS.

Changing it to HTTPS solves this.

@apaparazzi0329 - can you try to reproduce that with HTTP?
Maybe it means that something in your API uses a different version for HTTP and HTTPS.

**Comment by repjarms** [comment]
@GuyKh the Watson APIs don't support HTTP, and HTTPS is required in order to authenticate.

**Comment by GuyKh** [comment]
I'd argue that the endpoint should have a better, more informative, response than "text" field is missing.
But anyway. Thanks for the comment
